type: task

python: "3.11"

env:
  - CONFIG_PATH=configs/sample_config.yaml
  - NUM_ACCELERATORS=<Number of accelerators specified>

  - HUGGING_FACE_HUB_TOKEN=<Your Hugging Face access token>

commands:
  - conda install cuda
  - git clone https://github.com/huggingface/alignment-handbook.git
  - mkdir -p alignment-handbook/recipes/custom/
  - cp "$CONFIG_PATH" alignment-handbook/recipes/custom/config.yaml

  - cd alignment-handbook
  - python -m pip install .
  - python -m pip install flash-attn --no-build-isolation

  - pip install wandb
  - wandb login $WANDB_API_KEY

  - ACCELERATE_LOG_LEVEL=info accelerate launch --config_file recipes/accelerate_configs/multi_gpu.yaml --num_processes=$NUM_ACCELERATORS scripts/run_sft.py recipes/custom/config.yaml
ports:
  - 6006
  
resources:
  gpu:
    memory: 40GB
    name: A6000
    count: 2
